POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Link",
  "username": "notzelda",
  "password": "password123",
  "email": "notzelda@gmail.com",
  "profileImage": "https://i.pinimg.com/originals/19/72/77/1972776241251a3cea9fef51742a2b8f.jpg"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "notzelda",
  "password": "password123"
}
###
GET http://localhost:3000/api/auth/refresh
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGMwM2VjNWY4ZjdlYTg1MDgwMThjZTgiLCJpYXQiOjE2OTAzNzcyMjAsImV4cCI6MTY5MDM3NzgyMH0.5GEMBx8ZNetY_4oKvjFdezFs0FKKKQd-IucBF9Heil
###
GET http://localhost:3000/api/auth/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGJhY2VmMzk1YmEzZDFhMTQ3OGUxMDMiLCJpYXQiOjE2ODk5NzA1ODMsImV4cCI6MTY4OTk3MTE4M30.tAzQMf2IJNkA3KH8js8ajY4aKlUsfHr1zFSsecN_UMU


### api/user/tweets
POST http://localhost:3000/api/user/tweets
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGMyNTMzOTBlNjYxMmU3Yzc1MWM4YmIiLCJpYXQiOjE2OTA0ODM4MjksImV4cCI6MTY5MDQ4NDQyOX0.5vDRlEj6AKHaZZHbeWlSpmf5WChvbm68jPLn5JNhxGM
Content-Type: "multipart/form-data"

{
  "text": "Resposta",
  "replyTo": "64c259470e6612e7c751c8bd"
}

### api/tweets
GET http://localhost:3000/api/tweets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGMyNTMzOTBlNjYxMmU3Yzc1MWM4YmIiLCJpYXQiOjE2OTA0ODY4OTIsImV4cCI6MTY5MDQ4NzQ5Mn0.h6CjYun_FP7VbPU9L8pNoyRtSgNEJWFoVzEpC7Zrx7I

###
GET http://localhost:3000/api/tweets/64c259470e6612e7c751c8bd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGMyNTMzOTBlNjYxMmU3Yzc1MWM4YmIiLCJpYXQiOjE2OTA1NzE2NDcsImV4cCI6MTY5MDU3MjI0N30.utrYB3eT5lFyGVaNGpj_w9FuX8TQ-LWluaKFPyGF6Mc

###
GET http://localhost:3000/api/tweets?query=hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGMyNTMzOTBlNjYxMmU3Yzc1MWM4YmIiLCJpYXQiOjE2OTA2NTI2NTgsImV4cCI6MTY5MDY1MzI1OH0.drQHsKZPINa1jUvdACA0XSI--6EqRlsnpdobZU8_uY4